notifications:
  commits:      commits@juneau.apache.org
  issues:       issues@juneau.apache.org
  pullrequests: dev@juneau.apache.org
  jira_options: link label worklog
  jobs:         dev@juneau.apache.org
  discussions:  issues@juneau.apache.org